/**
 * Types Barrel Export
 * Centralized type definitions
 */

// Types are defined using JSDoc comments
// This file serves as a central location for type documentation

/**
 * @typedef {Object} Country
 * @property {string} id
 * @property {string} name
 * @property {string} code
 */

/**
 * @typedef {Object} SKU
 * @property {string} id
 * @property {string} name
 * @property {string} category
 */

/**
 * @typedef {Object} Month
 * @property {string} key
 * @property {string} label
 * @property {string} year
 * @property {boolean} isCurrentMonth
 * @property {boolean} isPast
 */

/**
 * @typedef {Object} PurchaseOrder
 * @property {string} id - PO identifier (e.g., PO-2025-001)
 * @property {string} status - Draft | Approval Requested | Approved | Rejected | Confirmed to UP | Shipped | Received
 * @property {Array<string>} orderItemIds - Linked order item IDs
 * @property {number} totalQtyCartons - Sum of all order items
 * @property {Array<string>} countries - Countries in this PO
 * @property {Array<string>} skus - SKUs in this PO
 * @property {string|null} requestedBy - LO who requested approval
 * @property {string|null} requestedOn - When approval was requested
 * @property {string|null} approvedBy - Manager who approved
 * @property {string|null} approvedOn - When approved
 * @property {string|null} confirmedBy - LO who confirmed to UP
 * @property {string|null} confirmedOn - When confirmed to UP
 * @property {string} createdBy
 * @property {string} createdOn
 * @property {string} modifiedBy
 * @property {string} modifiedOn
 * @property {Array<OrderHistoryEntry>} history
 * @property {Array<OrderItem>} orderItems - List of order items belonging to this PO (enriched)
 */

/**
 * @typedef {Object} OrderItem
 * @property {string} id
 * @property {string} countryId
 * @property {string} countryName
 * @property {string} skuId
 * @property {string} skuName
 * @property {string} status - Forecasted | Planned | Confirmed to UP | Partially Allocated | Fully Allocated | Shipped | Received
 * @property {number} qtyCartons
 * @property {string} deliveryMonth
 * @property {string|null} poId - Link to Purchase Order
 * @property {string|null} originalOrderItemId - If pushed from another order item
 * @property {boolean} isSystemGenerated - true if generated by Azure function
 * @property {string} channel
 * @property {boolean} tender
 * @property {string} comments
 * @property {string} createdBy
 * @property {string} createdOn
 * @property {string} modifiedBy
 * @property {string} modifiedOn
 * @property {Array<OrderHistoryEntry>} history
 */

/**
 * @typedef {Object} Forecast
 * @property {string} id
 * @property {string} countryId
 * @property {string} skuId
 * @property {string} monthKey
 * @property {number} forecastQty
 * @property {number} budgetQty
 * @property {number|null} actualQty
 * @property {string} createdBy
 * @property {string} createdOn
 * @property {string} modifiedBy
 * @property {string} modifiedOn
 */

/**
 * @typedef {Object} Allocation
 * @property {string} id
 * @property {string} orderItemId
 * @property {string} countryId
 * @property {string} skuId
 * @property {number} allocatedQty
 * @property {string} allocationMonth
 * @property {string} status
 * @property {string} createdBy
 * @property {string} createdOn
 */

/**
 * @typedef {Object} Shipment
 * @property {string} id
 * @property {string} orderItemId - Reference to OrderItem
 * @property {string|null} poId - Reference to PurchaseOrder
 * @property {string} countryId
 * @property {string} countryName
 * @property {string} skuId
 * @property {string} skuName
 * @property {string} shipmentNumber
 * @property {number} qtyCartons
 * @property {string} shipDate
 * @property {string} deliveryDate
 * @property {string} status
 * @property {string} carrier
 * @property {string} trackingNumber
 */

/**
 * @typedef {Object} OrderHistoryEntry
 * @property {string} action
 * @property {string} by
 * @property {string} date
 */
